'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HumansDo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property __() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("!", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AppIcons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_Panel_62() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control Panel 62", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_attachment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_attachment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_attachment1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_attachment1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_187() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder 187", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_tasks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-tasks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears_animated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears_animated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears_animated1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears_animated1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears_animatedBW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears_animatedBW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gears_animatedBWsmaller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears_animatedBWsmaller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_9000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 9000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_90001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 90001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_9000manja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 9000manja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_9000manja1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 9000manja1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_9000manja2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 9000manja2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HAL_9000manja3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HAL 9000manja3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hardware___Devices_299() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hardware & Devices 299", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property humansDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("humansDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property humansDO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("humansDO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property humansDO2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("humansDO2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property i() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("i", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Network_386() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network 386", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Network_395() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network 395", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_pinned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_pinned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paperclip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paperclip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pie_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie-chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pie_chart1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie-chart1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pie_chart2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie-chart2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property run_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property run_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property run_241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security___Alert_432() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security & Alert 432", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security___Alert_433() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security & Alert 433", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security___Alert_436() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security & Alert 436", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security___Alert_440() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security & Alert 440", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security___Alert_446() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security & Alert 446", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Start_Menu_476() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start Menu 476", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Start_Menu_493() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start Menu 493", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SYSTEM_ALERT_CAUTION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SYSTEM ALERT CAUTION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SYSTEM_ALERT_NOTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SYSTEM ALERT NOTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SYSTEM_ALERT_NOTE_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SYSTEM ALERT NOTE ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SYSTEM_ALERT_NOTE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SYSTEM ALERT NOTE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SYSTEM_ALERT_STOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SYSTEM ALERT STOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property upitnik() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upitnik", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_523() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 523", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wheels16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wheels16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
